namespace Inventory.Application.Responses;

public class ReorderSuggestionResponse
{
    public int Id { get; set; }
    public int InventoryItemId { get; set; }
    public string ProductId { get; set; }
    public string ProductName { get; set; }
    public string? VariationId { get; set; }
    public string SKU { get; set; }
    public int CurrentQuantity { get; set; }
    public int QuantityAvailable { get; set; }
    public int ReorderPoint { get; set; }
    public int SuggestedOrderQuantity { get; set; }
    public int SupplierId { get; set; }
    public string SupplierName { get; set; }
    public decimal EstimatedCost { get; set; }
    public int EstimatedLeadTimeDays { get; set; }
    public DateTime? EstimatedArrivalDate { get; set; }
    public string Priority { get; set; }
    public string Status { get; set; }
    public DateTime SuggestionDate { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? PurchaseOrderNumber { get; set; }
}
