// Inventory Service Models

export interface IInventoryItem {
  id: number;
  productId: string;
  productName: string;
  variationId?: string;
  sku: string;
  quantityOnHand: number;
  quantityReserved: number;
  quantityAvailable: number;
  reorderPoint: number;
  reorderQuantity: number;
  lowStockThreshold: number;
  warehouseId?: string;
  warehouseName?: string;
  location?: string;
  isActive: boolean;
  lastStockUpdateDate?: Date;
}

export interface IReorderSuggestion {
  id: number;
  inventoryItemId: number;
  productId: string;
  productName: string;
  sku: string;
  currentQuantity: number;
  quantityAvailable: number;
  reorderPoint: number;
  suggestedOrderQuantity: number;
  supplierId: number;
  supplierName: string;
  estimatedCost: number;
  estimatedLeadTimeDays: number;
  estimatedArrivalDate?: Date;
  priority: string;
  status: string;
  suggestionDate: Date;
  isAutoGenerated: boolean;
  purchaseOrderNumber?: string;
}

export interface IWarehouse {
  id: number;
  warehouseCode: string;
  name: string;
  description: string;
  addressLine1: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  contactPerson?: string;
  contactPhone?: string;
  totalCapacity: number;
  usedCapacity: number;
  availableCapacity: number;
  isActive: boolean;
  isPrimary: boolean;
  priority: number;
}

export interface IStockTransfer {
  id: number;
  transferNumber: string;
  fromWarehouseId: number;
  fromWarehouseName: string;
  toWarehouseId: number;
  toWarehouseName: string;
  productId: string;
  productName: string;
  sku: string;
  quantity: number;
  status: string;
  requestDate: Date;
  shipDate?: Date;
  expectedArrivalDate?: Date;
  actualArrivalDate?: Date;
  trackingNumber?: string;
  requestedBy: string;
  reason: string;
}
