namespace Inventory.Core.Entities;

/// <summary>
/// System-generated reorder suggestions based on stock levels and rules
/// </summary>
public class ReorderSuggestion : EntityBase
{
    public int InventoryItemId { get; set; }
    public string ProductId { get; set; }
    public string ProductName { get; set; }
    public string? VariationId { get; set; }
    public string SKU { get; set; }

    // Current stock status
    public int CurrentQuantity { get; set; }
    public int QuantityReserved { get; set; }
    public int QuantityAvailable { get; set; }
    public int ReorderPoint { get; set; }

    // Suggestion details
    public int SuggestedOrderQuantity { get; set; }
    public int SupplierId { get; set; }
    public string SupplierName { get; set; }
    public decimal EstimatedCost { get; set; }
    public int EstimatedLeadTimeDays { get; set; }
    public DateTime? EstimatedArrivalDate { get; set; }

    // Priority and status
    public string Priority { get; set; } = "Medium"; // Low, Medium, High, Critical
    public string Status { get; set; } = "Pending"; // Pending, Approved, Ordered, Rejected
    public DateTime SuggestionDate { get; set; } = DateTime.UtcNow;
    public DateTime? ReviewedDate { get; set; }
    public string? ReviewedBy { get; set; }
    public string? RejectionReason { get; set; }

    // Auto-reorder tracking
    public bool IsAutoGenerated { get; set; }
    public int? AutoReorderRuleId { get; set; }
    public string? PurchaseOrderNumber { get; set; }

    public string? Notes { get; set; }

    // Navigation
    public InventoryItem InventoryItem { get; set; }
}
