using Inventory.Application.Responses;
using MediatR;

namespace Inventory.Application.Commands;

public class CreateReorderSuggestionCommand : IRequest<ReorderSuggestionResponse>
{
    public int InventoryItemId { get; set; }
    public int SuggestedOrderQuantity { get; set; }
    public int SupplierId { get; set; }
    public string Priority { get; set; } = "Medium";
    public bool IsAutoGenerated { get; set; }
    public int? AutoReorderRuleId { get; set; }
    public string? Notes { get; set; }
}
